// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = ContentSliceSlice | TitleBlockSlice;

type BlogDocumentDataSlices1Slice = TitleBlockSlice | ContentSliceSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<BlogDocumentDataSlices1Slice>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, 'blog', Lang>;

export type AllDocumentTypes = BlogDocument;

/**
 * Primary content in *ContentBlock → Primary*
 */
export interface ContentSliceSliceDefaultPrimary {
  /**
   * Content Field field in *ContentBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.primary.content_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content_field: prismic.RichTextField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentSliceSliceVariation = ContentSliceSliceDefault;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSlice = prismic.SharedSlice<
  'content_slice',
  ContentSliceSliceVariation
>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceDefaultPrimary {
  /**
   * Text Field field in *TitleBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_block.primary.text_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_field: prismic.RichTextField;
}

/**
 * Default variation for TitleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TitleBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleBlock*
 */
type TitleBlockSliceVariation = TitleBlockSliceDefault;

/**
 * TitleBlock Shared Slice
 *
 * - **API ID**: `title_block`
 * - **Description**: TitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSlice = prismic.SharedSlice<
  'title_block',
  TitleBlockSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogDocumentDataSlices1Slice,
      AllDocumentTypes,
      ContentSliceSlice,
      ContentSliceSliceDefaultPrimary,
      ContentSliceSliceVariation,
      ContentSliceSliceDefault,
      TitleBlockSlice,
      TitleBlockSliceDefaultPrimary,
      TitleBlockSliceVariation,
      TitleBlockSliceDefault,
    };
  }
}
