// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  content_slice: dynamic(() => import('./ContentBlock')),
  title_block: dynamic(() => import('./TitleBlock')),
};
